name: reserve
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: 4.2.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: ^6.1.1
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  table_calendar: 3.0.9
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  google_maps_flutter: ^2.1.1 # Use the latest version available
  flutter_dotenv: ^5.0.2 # If using environment variables for API keys
  geolocator: ^8.0.1
  dropdown_model_list: ^2.0.0
  image_picker: ^1.0.5
  lottie: ^2.7.0
  shimmer: ^3.0.0
  geocoding: ^2.1.1
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9
  permission_handler: ^11.1.0
  timer_count_down: ^2.2.2
  connectivity_plus: ^5.0.2
  get: ^4.6.6
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.14.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  animate_do: ^3.1.2
  google_sign_in: ^6.2.0
  flutter_facebook_auth: 5.0.11
  firebase_auth_web: ^5.8.12
  faker: ^2.1.0
  firebase_app_check: ^0.2.1+8
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  marquee: ^2.2.3
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  firebase_storage: ^11.6.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0
  flutter_launcher_icons: ^0.13.1



  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ReserveLogo.png"
  adaptive_icon_foreground: "assets/icons/logo_foregound.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/l10n/
    - assets/icons/SwimmingPools.jpg
    - assets/icons/HorseRiding.jpg
    - assets/icons/FootballStadiums.jpg
    - assets/icons/PersonalTrainer.jpg
    - assets/audios/success-sound.wav
    - assets/icons/booking.jpg
    - assets/images/locationdialogImg.png
    - assets/images/authImg.png
    - assets/images/authImg1.png
    - assets/icons/
    - assets/icons/services.png
    - assets/icons/Xbtn.png
    - assets/icons/wazeIcon.png
    - assets/icons/cameraicon.png
    - assets/icons/ReserveLogo.png
    - assets/icons/logo_foregound.png
    - assets/images/user.png
    - assets/icons/bank-card.png
    - assets/icons/cashicon.png
    - assets/icons/location.png
    - assets/icons/expand_more_arrow.png
    - assets/icons/expand_less_arrow.png
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - lib/
    - assets/run.json
    - assets/bigcloud.json
    - assets/cloud.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages